### PR TITLE
Implemented auto-refresh ( #11 )

### LINKED ISSUE #11: Features: please add refresh command
Features: please add refresh command
so that I can see the pdf results every time I compile latex files

### PR DESCRIPTION
**Pull request by GeorchW**
See title - added auto-refresh. Fixes #11 .

### CODE REVIEW

**Comment by tomoki1207** [comment]
Great work! 👍

**Comment by GeorchW** [comment]
Hey, nice! Are you going to publish a new version soon?

**Comment by tomoki1207** [comment]
I intend to do so.
But, it seems that it will not work due to package updates, so I will fix it and publish it.

**Comment by hiiwave** [comment]
Thanks for the great work! Just want to confirm if auto-refresh is working now? I seem to be unable to get it work.

**Comment by tani** [comment]
@hiiwave In my environment, Visual Studio Code 1.56.2 in macOS Big Sur, it works fine. What are you using?

**Comment by hiiwave** [comment]
Hi @tani thanks for the info. It's windows 10. I don't know the vscode version. I am with a different computer now thus I cannot check it at this moment.

**Comment by tani** [comment]
At least, v0.6.0 has this function and you might install the latest version v1.1.0 released in July 2020. I used the latest one. I don't know much but I guess the reason is breaking compatibility of file watching API between OS, the editor, and this extension. The file watching facilities often be broken even if Linux and others.  Please type updating all of them.

**Pull request merged**
